from setuptools import setup

setup(
    name="diffgeo",
    url="https://github.com/math142-FA21/auppal.git",
    version="0.0.1",
    author="Abhinuv Uppal",
    author_email="auppal22@students.claremontmckenna.edu",
    maintainer="Abhinuv Uppal",
    maintainer_email="auppal22@students.claremontmckenna.edu",
    keywords="differential geometry statistics network graph finance stocks time series ricci curvature",
    license="LICENSE.md",
    description="Code for Abhi Uppal's Math 142 Project",
    long_description=open("README.md").read(),
    py_modules=["diffgeo", "diffgeo.data"],
    package_data={"": ["*.csv"]},
    include_package_data=True,
    install_requires=[
        "aiohttp",
        "aiolimiter",
        "backoff",
        "bidict",
        "black==21.7b0",
        "datetime",
        "dvc[gdrive,gs]",
        "flake8==3.9.2",
        "matplotlib",
        "nbclient",
        "nbdime",
        "nbconvert",
        "nbdev",
        "nbformat",
        "notebook",
        "numpy",
        "openpyxl",
        "pandas",
        "pandasql",
        "plotly==5.3.1",
        "python-dotenv",
        "pytz",
        "ratelimit",
        "scipy==1.7.1" "yfinance",
    ],
)
